######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 10 09:24:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Missile.h Tank.h TankConst.h TankWindow.h
SOURCES += main.cpp Missile.cpp Tank.cpp TankWindow.cpp
RESOURCES += resource.qrc
